In [1]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
# simple python list
a=[1,2,3.2,4,5,"hello"] #list can hold  multiple data type
a


[1, 2, 3, 4, 5, 'hello']

In [ ]:
np.array(a)    
# nichay output main u21 likha a gia ha iska matlab ha sara data string main covert ho gia ha

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [13]:
b = [1,2,3.4,4,5]
b
# ab main is list main aik flot rakha ha isko numpy array main dakhtay hain yah kia karta ha 

[1, 2, 3.4, 4, 5]

In [ ]:
np.array(b)     #is main numpy nay list ki sari values float main convert kar di hain hence proved same data type matters

array([1. , 2. , 3.4, 4. , 5. ])

vector and matrix vector is one dimensional ,matrix is two dimensional  vector is simple list and simple python list can not support two dimensional list

In [ ]:
#vector is simple  list
l=([1,2,4,4],[1,3,4,5],[6,7,8,9])
l
#list is two dimensional but looking like one dimensional 


([1, 2, 4, 4], [1, 3, 4, 5], [6, 7, 8, 9])

In [16]:
#matrix or two dimensional list in array
np.array(l)

array([[1, 2, 4, 4],
       [1, 3, 4, 5],
       [6, 7, 8, 9]])

array generation function

In [20]:
arr= np.arange(1,11,2)   #arange function of numpy works just like range in a list
arr         #3s rule

array([1, 3, 5, 7, 9])

In [26]:
arr=np.zeros(6)
arr  #zeros function of numpy to create a list of zero 

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# above one is one dimensional if i want two dimensional
arr=np.zeros((6,6)) #just write 6,6 means rows into columns  
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
arr=np.ones((3,4)) #for matrix wrrite in double brackets 
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linsspace is known as linear space

In [ ]:
arr=np.linspace(1,5,2) #strat stop space means kay mujhe 1 aur 5 kay darmayan 2
#ka space chahiya
arr       #more example down

array([1., 5.])

In [ ]:
arr=np.linspace(1,6,10)  #1 sy 6 kay darmayan 10 number genrate karay ga
arr  #ab 1 sayy 6  tak number print hovay hain aur har number kay darmayan 10 ka space  ha

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

#random generation functions
jab values 0 and 1 kay darmyan ati hain osko noramlization kahtay hain 
jab values 3 and -3 kay darmayn ati hain ussko standardization kahtay hain 

In [ ]:
np.random.rand(6) #rand is a function of random library 
#6 ka matlab ha 6 random values generate ho  jayen gi 
#jo 0 and 1  kay darmayan ho gi
#random library works with numpy 

array([0.08119092, 0.10327454, 0.0178767 , 0.72257552, 0.21442022,
       0.36329612])

In [34]:
# standardization use randn funcction
np.random.randn(8)


array([ 0.00993346,  0.82681515, -0.4454013 ,  0.92112594, -1.16807364,
        0.54116038,  0.91976911, -0.5482984 ])

In [ ]:
np.random.randint(6)   #randit use  to generate any random number depends 


1

In [10]:
import numpy as np
np.random.randint(10,20,10)#(low point,highpoint,generate random numbers)

array([12, 17, 10, 18, 15, 12, 12, 16, 10, 15], dtype=int32)

In [ ]:
# attributes are variable defined  inside a class attributes are not called methods are called

Array  attribute

In [12]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#shape  attribute attribute kay agay bracket ni lagta directly likha jata ha 
arr.shape

(3, 3)

In [14]:
arr.size  #size attribute

9

In [16]:
arr.dtype  #some basic attribute only

dtype('int64')

array methods 1st minimum method froom above matrix vvector array whatever you can say it  is what it is

In [18]:
arr.min()

np.int64(1)

In [19]:
arr.max()

np.int64(9)

In [ ]:
arr.sum() #inbuilt function of  python

np.int64(45)

In [ ]:
np.sum(arr,axis=0) #sum of column in using numpy axis method axis zero means columns an daxis 1 mean row

array([ 6, 15, 24])

In [22]:
#mean
arr.mean()

np.float64(5.0)

In [23]:
#standard deviation
arr.std()

np.float64(2.581988897471611)

In [24]:
arr.argmax()  #used to find index of maximum element

np.int64(8)

In [25]:
arr.argmin()

np.int64(0)

reshaping and  resizing   it means we have an array and we want to reshape and resize it

In [5]:
import numpy as np 
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr=arr.reshape(6,5) #while converting keep in mind to count all the numbers so that all the numbers can fit in the matrix
 #is main hum upar wali one dimensonal array ko 3 dimensional main convert karain gay

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

there first session about how array are created  is completed which is about basics now we see slicing indexing and operations of array