In [2]:
import numpy as np

In [6]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Numpy slicing slicing means to remove a portion from an array for slicing we use index

In [7]:
arr[1:5]   #this goona slice out the number from index one untill index 5

array([12, 13, 14, 15])

In [ ]:
arr_slice=arr[3::2]
arr_slice  #last number is for step and 3 is starting index and 2 is  used  for step

array([14, 16, 18, 20])

Numpy indexing and  slicing  of matrix

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr   #2d array with 6 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5] #matrix index  is little differenet  from arrsy here a index value target a whole row and column

array([26, 27, 28, 29, 30])

In [ ]:
arr[1,1] #to target only one element in a matrix we write it as
    #row,colum

np.int64(7)

In [17]:
#for slicing a 2*2 matrix from a 6*5 matrix
slice=arr[0:2,1:3] 
slice

array([[2, 3],
       [7, 8]])

In [20]:
arr[3:7,3:7]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]   #for slicing out a column in a matrix it become  a vector
#this will be used in data frames jab hum machine learning kay algorithm parhain gay wahan humko convert karna parta ha data ki terms main

array([ 3,  8, 13, 18, 23, 28])

Boolean indexing

In [25]:
arr=np.arange(11,21) 
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr%2==0 #for filtering out spefic number i.e i need 
#even num here i will find out module of it 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

ab jo yahan par true false values aye hain unko array jo upar variable arr ha us main store kar kay chalain gay jo true value houn gi wo execute ho jayen gi

In [ ]:
arr=arr[bool_index]  #yahan saray kay saray even element a  jayen gay humaray pas
arr

array([12, 14, 16, 18, 20])

here our  numpy index get completed in next repo i will cover array operations